- README.md
Sorry for this tiny change, but I just happen to see if while reading the README.
> Link name to React Query in README fixed

- README.md
Hi there,
I noticed that `items` is no longer returned from the hook in the latest release, so I changed it to `virtualItems` in the docs. Would be great if you could also update the version of `react-virtual` used in the Codesandbox!
Kind regards,
Hampus Kraft.
> docs: fix incorrect variable names

- examples/sandbox/src/InfiniteScroll.js
When visiting the [project demo](https://codesandbox.io/s/elegant-jackson-n9bgg?file=/src/InfiniteScroll.js:0-3873) I noticed the infinite scrolling demo was not working. The reason seemed to be the source we were fetching data from has crashed.
Creates a helper demo function that overrides the axios plugin for GET and injects a “fake” response if a specific url is passed in. This allows a user who is playing with the demo to still plug in their favorite APIs without having to figure out how to set up a getter.
> fix(infinte-scroll-demo): restore demo functionality by creating fake api response

- src/index.js
- src/tests/index.test.js
- yarn.lock
Prevents infinite loop update by allowing zero measured value in [`size evaluation`](https://github.com/tannerlinsley/react-virtual/blob/master/src/index.js#L61).
Fixes https://github.com/tannerlinsley/react-virtual/issues/29
Might fix https://github.com/tannerlinsley/react-virtual/issues/43 (unfortunately for this issue, I can't reproduce it locally on my machine cc/ @estebansolisd)
@tannerlinsley I've added a test + I've tried examples to check any regression. Let me know if I have miss something.
**Screenshots:**
| Before | After |
| ------ | ----- |
| <img width="550" alt="Capture d’écran 2020-08-12 à 17 59 58" src="https://user-images.githubusercontent.com/10498826/90038697-0395b680-dcc6-11ea-9ec3-8b07f68397a5.png"> | <img width="553" alt="Capture d’écran 2020-08-12 à 18 00 10" …
> fix: infinite update loop with zero measured value

- src/useRect.js
Only height and width are used from rect object. No need to update state when this parameters did not change. 
This will fix unnecessary updates of parent component when scrolling the page.
> Prevent parent from unnecessary updates when scrolling window.

- src/index.js
The `range` state doesn't update in response of changes to `size` until the layout effect is applied. I don't want to update state within the render function, so adding a guard seems like the best approach.
Fixes #52
Might fix #49
> fix: return empty list when size is 0

- src/index.js
Probably should have tests for this, but I thought I'd throw this together to help push #64 along a bit.
Closes #64
> fix: don't do onScroll when there is no element

- examples/infinite-scroll/src/index.js
This example suggests to delete lines 9-24, It should infact be lines 9-36.  Fixing that.
> Fixing typo in line number

- src/index.js
> fix: don't attach event listeners when there's no element

- README.md
- src/index.js
This PR should allow users (developers) to greatly increase performance of the tracking measurements of the `parentRef` in modern browsers.
It would also allow to remove `useRect` in production as part of the dead code removal.
> feat: Add ability to replace useRect with custom observer

- types/index.d.ts
I missed `react-virtual` has typings in the previous PR, so let me please fix it with this one.
> fix: typings for optional useObserver parameter

- package.json
This pull request to allow react 17 as peer dependency. This version of react should ([in theory](https://reactjs.org/blog/2020/10/20/react-v17.html#other-breaking-changes)) not break anything. At work we are currently on react 17, we've had no issue related to it and we are on the latest version of [react-virtual](https://github.com/tannerlinsley/react-virtual).
> chore: allow react v17 as peer dependency

- README.md
- src/index.js
This adds two new options which make it easier to customize the scroll
behavior.
`onScrollElement` which makes it possible to use a different
element to bind the `onScroll` event too.
`scrollOffsetFn` allows a custom function to calculate the offset rather
than using the `parentRef`'s width or height.
> feat: support custom scroll options

- README.md
- src/index.js
- types/index.d.ts
This PR introduces a `keyExtractor` option to the `useVirtual` hook, which allows dynamically measured items to be cached by unique ID. This will fix #83.
With these changes, the measure cache is no longer cleared when the list's `size` changes. I've been using these changes for an infinitely scrolling list of dynamically measured elements, and I haven't encountered any issues.
A few notes:
- I'm open to suggestions for a better name than `keyExtractor`. (I took the name `keyExtractor` from [React Native's `FlatList`](https://reactnative.dev/docs/flatlist#keyextractor).)
- There were a few lines in `src/index.js` that Prettier updated automatically.
- The only change I made to `types/index.d.ts` was to add `keyExtractor`…but this file's line endings were CRLF rather than LF. So, …
> feat: support caching dynamic measurements by unique key

- types/index.d.ts
This small PR fix measureRef type, and add missing onScrollElement, scrollOffsetFn
> fix: measureRef type in VirtualItem, add missing types in useVirtual

- .eslintrc
- README.md
- src/index.js
- types/index.d.ts
This PR add's 
* update eslint config to include a warning for useIsomorphicLayoutEffect
* add scrollOffsetFn to useIsomorphicLayoutEffect dependency list
* pass event from on scroll to scrollOffsetFn, with this we can easy detect if scrollOffsetFn was called while scroll.
> scrollOffsetFn not included in effect dependency list

- src/index.js
This fixes the IE11 issue I raised in #116. This doesn't change any behavior, so the change shouldn't affect anyone other than IE11 users.
> fix: replace Object.assign with property assignment

- README.md
> docs: add 'required' info to `estimateSize` description

- docs/src/components/Nav.js
- docs/src/components/Seo.js
The title still says `React Charts` 😬 
This PR just changes that to `React Virtual`
> fix: Page Title

- src/index.js
- src/tests/index.test.js
Yet another fix for #112 😅 Idea here is very simple, when measurements request for new range, but if scroll is happening in between cancel the request.
> fix: range calculated only on scroll

- docs/src/pages/index.js
Minor typo fix in the docs on the landing page:
"dyanmically" -> "dynamically"
> docs(index): Fix typo in 'dyanmically'

- docs/src/pages/docs/api.md
- src/index.js
- types/index.d.ts
This PR adds small optimisation when creating measurements, as we don't need to rebuild the list from start, only from where item size changed. In addition added `key` value on virtualItem.
closes #120
> perf: reuse already measure items, include key into virtualItem

- package.json
Today, the `types` field is defined as follows:
https://github.com/tannerlinsley/react-virtual/blob/5508e19db343bcf02193a8c977f75f56e3d282cc/package.json#L17
While this ends up working during type-check, this isn't helping the auto-import suggestion in VSCode:
(I assume the shortest option from the same package is displayed, having `react-virtual/types` isn't ideal)
This is how it looks like after manually editing `node_modules/react-virtual/package.json` with this PR's changes (and restarting the TS server):
---
Additionally, this helps partial matching for autocomplete.
Before:
After:
> fix: Use `types/index.d.ts` for `types` field

- README.md
I've fixed the GitHub image shield for this repo in the README file which will now show the total number of stars that this repo has got.
Previously, it showed a ``repo not found`` error like the below screenshot,
> Fixed Github Image Shield to show stars

- examples/dynamic/src/index.js
- examples/infinite-scroll/src/index.js
- examples/variable/src/index.js
The dynamic examples were using heights from the generated data instead of the measurement. That is `${rows[virtualRow.index]}px` vs `${virtualRow.size}px`.
The variable example was doing the opposite (using `${virtualRow.size}px`) even though `ref={virtualRow.measureRef}` was never set in the variable example.
Also update the condition in infinite scroll (#161)
> Update the height and width values in examples

- packages/virtual-core/src/index.ts
Closes #298
Other changes:
it removes [a react import](https://github.com/TanStack/virtual/compare/beta...FaberVitale:fix-%23298?expand=1#diff-85d1b85f3d4e501779ca41e51cd38cf7f61a2b7ffddaf958cd7e79c2787c36f1L3)
> fix: remove unnecessary imports from `virtual-core/src/index.ts` #298

- .github/workflows/pr.yml
- packages/react-virtual/package.json
- packages/react-virtual/yarn.lock
Closes #300 
- Updates `packages/react-virtual/yarn.lock`
- drops `node 12` from `pr.yaml` matrix [EOL 30 April 2022](https://azure.microsoft.com/en-us/updates/node12/)
> fix: missing peerDep of @tanstack/react-virtual #300

- README.md
Rename based url from `https://github.com/@tanstack` to `https://github.com/TanStack`
> fix: Rename broken url links

- packages/virtual-core/src/index.ts
Hi everyone, thanks for making this awesome library!
The goal of this PR is to add strict mode support for React v18
React v18 in strict mode runs `useEffect` twice in dev mode, as documented in [ReactJS blog](https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors)
For this reason, the `cleanup` function is called after the initial mount of the component, which does call/clear `this.unsubs`, but the scrolling element `this.scrollElement` remains set.
When `useEffect` runs the second time, the `_willUpdate` if check
```js
if (this.scrollElement !== scrollElement) {...
```
evals as `false`, and prevents new subs from being set, resulting in broken virtualisation behaviour, as noted in issue #322 
This PR aims to solve the issue by enhancing the cleanup function so the …
> Add React v18 strict mode support

- packages/virtual-core/src/index.ts
> fix: Export `ScrollToOptions` interface for TS

- packages/virtual-core/src/index.ts
Only notify clients when the range of items changes, thus avoiding many unnecessary updates. Also improves smooth scrolling performance, which equally triggered massive amounts of re-renders.
The current behavior can still be obtained in user-land by simply attaching a scroll listener to the `scrollElement` and calling `measure()` in the event handler
**Note**: So far only tested with the react-virtual adapter
Fixes #352 
---
_Reduces re-renders from this: (watch the re-renders)_
https://user-images.githubusercontent.com/15364860/181907731-3ab351f9-d706-4066-ac7e-1337af0ed7ff.mov
_To this:_
https://user-images.githubusercontent.com/15364860/181907738-534605ce-6e2f-45d6-9197-4c4961731d26.mov
> Only re-render on range changes

- package-lock.json
- packages/react-virtual/package.json
- packages/solid-virtual/package.json
- packages/svelte-virtual/package.json
- packages/virtual-core/package.json
- packages/virtual-core/src/index.ts
- yarn.lock
Reduces idle CPU usage and should also improve scrolling performance. The previous approach used a `requestAnimationFrame()` loop with calls to `getBoundingClientRect()` on every frame.
Fixes https://github.com/TanStack/virtual/issues/359
Before
After (+ dark mode 😄):
Verified it still works, the number of items increase and decrease when resizing:
https://user-images.githubusercontent.com/15364860/182487611-ec7a2635-e86f-4961-89a5-67908b9641e5.mov
> feat: Use ResizeObserver to listen to size changes

- packages/virtual-core/src/index.ts
Make sure the first render has the correct range.
Before (no `initialRect`, renders initially always `overscan` + 1):
After (with `initialRect`, docs example with height set to 200px):
> fix: Fix `initialRect` not working

- docs/api/virtualizer.md
- packages/virtual-core/src/index.ts
From the commit message:
> Allow to explicitly override `smoothScroll` when calling scrollToOffset()/scrollToIndex(). Fall back to the global option `enableSmoothScrolling` when the parameter is not explicitly set.
The default behavior is unchanged. That is, when `enableSmoothScroll` is set to true, both scrollToIndex() and scrollToOffset() use smooth scrolling, and if false they don't.
This makes it possible to set the smooth scrolling behavior at the call-site, which is more flexible. Example usage:
```js
scrollToIndex(10, { smoothScroll: false }) // Explicitly set smooth scroll
scrollToIndex(10, { align: 'center', smoothScroll: false }) // Also explicitly set alignment
scrollToIndex(10) // Falls back to `options.enableSmoothScroll`
```
---
Note: I failed to link the package locally so …
> feat: Allow explicitly overriding `smoothScroll` in scrollToIndex()/scrollToOffset()

- packages/virtual-core/src/index.ts
Explicitly scroll to the correct offset.
The range was initially calculated correctly, but the scroll position of `scrollElement` was 0 (which causes the range to be re-calculated to match the visible area). The same applies for SSR usage: the scroll position cannot be transmitted from the server, so it needs to be restored explicitly on the client.
**Note**: Needs to be tested with a SSR setup
Fixes https://github.com/TanStack/virtual/issues/346
> Fix `initialOffset` not working

- packages/react-virtual/__tests__/index.test.tsx
- packages/virtual-core/src/index.ts
fixes https://github.com/TanStack/virtual/issues/363
suppress https://github.com/TanStack/virtual/pull/403
> Trigger recalculation on every update when not scrolling

- docs/api/virtual-item.md
- docs/api/virtualizer.md
- examples/react/dynamic/src/main.tsx
- package-lock.json
- package.json
- packages/react-virtual/__tests__/index.test.tsx
- packages/react-virtual/__tests__/jest.setup.js
- packages/react-virtual/src/index.tsx
- packages/solid-virtual/src/index.tsx
- packages/svelte-virtual/src/index.ts
- packages/virtual-core/src/index.ts
Was looking on our options how to add observing element for size changes using ResizeObserver fix #376. What if we would change a bit the api, end expose `measureElement` on top level, not on the item. This would allow use to memo few of them for example in grid and fix #391
Then we nee to bound `measureElement` with index, we can do it via `attribute` by adding `data-index={virtualRow.index}`.
> Observe element for size changes with ResizeObserver

- examples/react/sticky/package.json
We need it at here: https://github.com/TanStack/virtual/blob/beta/examples/react/sticky/src/main.tsx#L5
> Add the missing dependency "lodash" to package.json

- examples/react/dynamic/src/main.tsx
- packages/react-virtual/__tests__/index.test.tsx
- packages/virtual-core/src/index.ts
> fix(virtual-core): fix scrollToIndex in dynamic

- examples/react/dynamic/src/main.tsx
- package-lock.json
- packages/react-virtual/package.json
- packages/virtual-core/src/index.ts
> fix(virtual-core): scrollToIndex align end gets "stuck"

- packages/vue-virtual/package.json
- packages/vue-virtual/src/index.ts
1. I have found a bug where after instantiating Virtualizer with empty array (count = 0), and later populating that array, will not show list at all. Since we are using `shallowRef`, we need to `triggerRef` in order for list to be updated, not only in onChange handler (which will be triggering if scroll available) but in watcher for options as well. 
2. It would be really great if we could use adapter for Vue2.7 as well, considering same primitives used for this adapter seem to work in v2.7 also. I implemented this manually in Vue2.7 with `virtual-core` and current beta code from vue-virtual, and it works just nicely (with the aforementioned fix). 
I also updated Vue version in peerDependencies to allow installation in Vue2.7, dunno if that is enough for this to work for 2.7, opinions …
> Bugfix:  dynamically changing data structure is not reactive

- packages/react-virtual/src/index.tsx
- packages/solid-virtual/src/index.tsx
- packages/svelte-virtual/src/index.ts
- packages/vue-virtual/src/index.ts
currently the `@tanstack/react-virtual` package throws `useLayoutEffect does nothing on the server` warnings during ssr when using a deno runtime. this is because deno has a global window object available for browser compatibility (though is being considered for removal https://github.com/denoland/deno/issues/13367). also see [here](https://remix.run/docs/en/v1/pages/gotchas#typeof-window-checks) for further reading.
this pr replaces all `typeof window` checks across all packages with `typeof document` instead which works in all environments.
prior art: https://github.com/framer/motion/pull/1522
> fix: replace typeof window checks with typeof document

- packages/virtual-core/src/index.ts
Currently, the borderBoxSize property in ResizeObserverEntry is not supported on Safari. This can cause errors and unexpected behavior in applications that rely on this property. This pull request proposes the addition of an unsupported type guard for Safari's borderBoxSize to prevent errors and improve the user experience.
Added optional chaining to the borderBoxSize type guard in ResizeObserverEntry for browsers that do not support this property.
> Add unsupported type guard for Safari `borderBoxSize`

- docs/api/virtual-item.md
- docs/api/virtualizer.md
- examples/react/variable/src/main.tsx
- packages/virtual-core/src/index.ts
This PR aims at adding support to masonry layouts as expressed in #30
In terms of logic the difference is that instead of taking the previous element in the list, it looks for the one that's the furthest away from the end of the container.
For example in a top to bottom list with two columns and these elements:
```
----------- -----------
|    1    | |    2    |
|         | -----------
-----------
```
The third element should be inserted below box 2 and not box 1 because box 2 is the one that's the furthest from the end of the container.
```
----------- -----------
|    1    | |    2    |
|         | -----------
----------- -----------
|    3    |
|         |
-----------
```
The fourth element would be inserted below box 1.
I updated the docs and added an example to the variable examples: …
> feat: add support for masonry

- docs/api/virtualizer.md
I couldn't find `createWindowVirtualizer` so I assumed it is meant to be updated. 🙂
> fix: virtualizer api doc

- docs/api/virtualizer.md
- packages/virtual-core/src/index.ts
just a small refactor, it also provides a solution for the ResizeObserver loop limit error
> manually resize the calculated size of an item

- packages/virtual-core/src/index.ts
If a user scrolls the page before `useWindowVirtualizer` is called, the scroll position will be reset to 0. This fixes that issue.
> (Fix) calling useWindowVirtulizer reset's page scroll to 0

- docs/api/virtualizer.md
As this function should not change on every re-render, that should be mentioned in the docs.
> Update getItemKey description

- examples/react/dynamic/src/main.tsx
- packages/react-virtual/__tests__/index.test.tsx
- packages/virtual-core/__tests__/index.test.ts
- packages/virtual-core/src/index.ts
> fix: prevent returning items when container size is zero

- docs/guide/introduction.md
Introduction page of the documentation has the mention of incorrect hook - `useVirtual`, which is not present in the code. `useVirtualizer` name should be used instead.
> Use correct hook name on Introduction page

- docs/api/virtualizer.md
There is currently a mismatch of the documentation and the definition/handling in the code regarding the `resizeItem` method which is utilized to adjust the size of an item. 
After a prior update (https://github.com/TanStack/virtual/commit/3270b6c38a6ea699f36e72a05729b274a6c5335b) the first [argument](https://github.com/TanStack/virtual/blob/62d6dc8cf917e8500b4709a59a46f936d9252f61/packages/virtual-core/src/index.ts#L651) got changed from being an item index (= `number`) to a reference of an `virtualItem` itself. With the alignment in the docs it consistency in usage will be ensured.
> Update documentation of `resizeItem`

- docs/api/virtualizer.md
The return type for `getScrollElement` is `TScrollElement | null`. 
`undefined` is not a valid option.
> Replace `undefined` with `null` in the `getScrollElement` API description.

- packages/virtual-core/src/index.ts
In my application I have a waterfall style layout so the last item is not guaranteed to be the furthest away. I was having issues with the sizing not being correct, so after digging in I found the root cause and implemented a fix.
Example of my measurements array (look at the last 2 items and notice the 2nd to last has a greater end property):
I also included a small optimization for one lane. I am happy to tweak the logic in any way so just let me know. Happy to contribute!
> Bug Fix: Calculate getTotalSize correctly when using multiple lanes

- packages/virtual-core/src/index.ts
Encountered an error while running `tsc` with the `--declaration` flag:
`Exported variable 'x' has or is using name 'Rect' from external module "node_modules/@tanstack/virtual-core/build/lib/index" but cannot be named.`
Fix is to simply export related interface from index.ts
> fix: error while running tsc with --declaration flag

- docs/api/virtualizer.md
Looks like the `lanes` documentation was under the wrong grouping within `virtualizer.md`. This PR simply re-locates it to `Optional Options`.
> docs: Move lanes under the correct section

- packages/virtual-core/src/index.ts
- packages/virtual-core/src/utils.ts
As scrollend event is supported by almost all major browser ( without safari ) we can use it to detect scroll completion, in this change the observeElementOffset type signature changed, current it will be not only responsible to return scroll offset but also if is scrolling.
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollend_event
https://developer.chrome.com/blog/scrollend-a-new-javascript-event/
> feat: detect scroll completion with scrollend event

- packages/vue-virtual/src/index.ts
This solves https://github.com/TanStack/virtual/issues/715
According to the [Vue docs](https://vuejs.org/guide/essentials/watchers.html#callback-flush-timing); watchers will run their effects after state updates but before DOM updates. The `ref` attribute performs the same way which is why some users discovered they need to wrap their `measureElement` calls with `nextTick` in order to measure elements in a post update state (https://github.com/TanStack/virtual/issues/619).
Currently the vue adapter will update state pre DOM update which causes an infinite loop if the estimated size of an element doesn't exactly match the measured size. Simply running the effect post DOM update will ensure that the elements are measured and taken into account before virtualizer updates its state.
> Run watcher post DOM update in Vue adapter

- docs/api/virtualizer.md
In https://github.com/TanStack/virtual/pull/439 (possibly previous commits)`scrollTo*` options argument was changed but docs weren't updated.
> docs(virtualizer): update scrollToFn/Offset/Index options

- docs/framework/vue/vue-virtual.md
Vue Virtual is released now, so this "coming soon" text seemed appropriate to remove.
> docs: remove "coming soon" from Vue Virtual docs title

- packages/virtual-core/src/index.ts
- packages/virtual-core/src/utils.ts
In multi window environment, where React is running in a main window/process and renders content to a different child window, the globals like `setTimeout`/`clearTimeout` will not work properly because it's using the main Window object and not the child one.
This PR adds support to multi-window.
`setTimeout` --> `targetWindow.setTimeout`
`clearTimeout` --> `targetWindow.clearTimeout`
`ResizeObserver` --> `targetWindow.ResizeObserver`
`targetWindow` is obtained from `scrollElement.ownerDocument.defaultView`. 
We have multi-windows use case, so we want to make sure that the globals work well with it. This is the reason for my PR.
I built an example of dynamic height list in child window:
https://stackblitz.com/edit/vitejs-vite-2zau9t?file=src%2FApp.tsx&terminal=dev
1. Open this example on …
> fix(virtual-core): add support to multi window

- docs/api/virtualizer.md
- examples/react/dynamic/src/main.tsx
- packages/virtual-core/src/index.ts
> feat(virtual-core): add enabled option

- docs/api/virtual-item.md
- docs/api/virtualizer.md
- packages/virtual-core/src/index.ts
As we can relay on node.isConnected to attach the RO or read size, like in `lit` integration https://github.com/TanStack/virtual/pull/718 we need to have another option to do. In this PR  https://github.com/TanStack/virtual/pull/737 let's add back the measureElement on virtual item and keep it stale via measureElementCache that has bound in scope index.
```
${ref(virtualRow.measureElement}
```
> feat: add measureElement on virtual item, when we can't relay on node.isConnected

- .github/workflows/autofix.yml
- packages/lit-virtual/README.md
- scripts/config.js
Related: https://github.com/TanStack/query/pull/7755
> ci: Add autofix.yml

- docs/api/virtualizer.md
The interface defines that the scroll behavior of the `scrollToIndex` function can be 'auto' or 'smooth'.
The documentation falsly stated 'auto' or 'scroll'
> docs: update API documentation of scrollToIndex

- packages/virtual-core/src/index.ts
This PR corrected key for the `getVirtualItems` memo.
> Correct key for getVirtualItems memo

- docs/api/virtualizer.md
- packages/virtual-core/src/index.ts
This change adds an option for consumers who need to switch between left-to-right and right-to-left language locales. 
With this change, scrolling left-to-right:
https://github.com/user-attachments/assets/93892f15-a5fe-4cdc-8ccf-45c316a966f0
Without this change, scrolling right-to-left:
https://github.com/user-attachments/assets/47aa1cae-de3d-4946-9fd8-29fee19fe560
With this change, scrolling right-to-left:
https://github.com/user-attachments/assets/ab87e0f7-0679-4669-986d-69188d572f7f
> feat: Support inverted horizontal scrolling for right-to-left locales

- packages/angular-virtual/package.json
Excluding .d.ts files from the package output results in TypeScript errors for consumers trying to install @tanstack/angular-virtual.
For example:
(from https://tanstack.com/virtual/latest/docs/framework/angular/examples/fixed)
This was a simple copy/paste error that I only noticed after the package was published, since the .d.ts files are present locally and only get excluded by the actual npm publish.
> fix(angular-virtual): fix build & remove unused scripts

- packages/angular-virtual/src/proxy.ts
Calls to 'getOffsetForAlignment', getOffsetForIndex', 'getVirtualItemForOffset', and 'indexFromElement' now work as expected instead of erroring with `TypeError: fn is not a function`.
> fix(angular-virtual): fix proxying of computed functions with args

- packages/virtual-core/src/index.ts
- packages/virtual-core/src/utils.ts
Hi, I checked the type of debug and it's`any`. But [this link](https://tanstack.com/virtual/latest/docs/api/virtualizer#debug) says boolean type, and I didn't understand why it was of type `any` either. so I changed it to boolean.
> chore: change type of `debug` from `any` to `boolean`

- docs/api/virtual-item.md
- packages/virtual-core/src/index.ts
This PR enhances `Key` type with `bigint` to align with `React.Key`. This was updated in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66723. This will enable us to use `React.Key` as type for where we require `Key` as type.
> fix(virtual-core): add bigint to Key to align with @types/react implementation

- packages/virtual-core/src/index.ts
fixes https://github.com/TanStack/virtual/issues/815
> fix: don't clear elementsCache on cleanup

- examples/vue/infinite-scroll/src/App.vue
This fixes a ref not being accessed with it's `.value` accessor, causing a boolean check to always be truthy.
> docs(examples): fix bug in Vue infinite scroll example

- docs/api/virtualizer.md
I had to re-read this sentence a several times until I understood the meaning. Perhaps adding punctuation and chaning the grammar sligthly improves readability?
> Improves readability

- docs/api/virtualizer.md
- packages/virtual-core/src/index.ts
fixes https://github.com/TanStack/virtual/issues/799
> fix: add `useScrollendEvent` option

- packages/react-virtual/src/index.tsx
When HMR is triggered `useEffect` cleanup function will call function returned from `instance._didMount()`.
This will set `scrollElement` to null and `Virtualizer` will stop working.
I added an additional check if `scrollElement` is null and if it is - call `instance._willUpdate()`.
This PR resolves https://github.com/TanStack/virtual/issues/750.
> fix(react-virtual): handle `scrollElement` cleanup after HMR

- packages/virtual-core/src/index.ts
calculateRange() returns a new object busting the memo cache on every call to getIndexes(). Passing the scalar startIndex and endIndex from calculateRange() fixes this issue.
> Avoid invalidating getIndexes memo cache on every call

- docs/api/virtualizer.md
- packages/virtual-core/src/index.ts
This pr exposes an API that used to be private (`getIndexes`) and makes it a new public API on the virtualizer called `getVirtualIndexes`.
For TanStack Table examples, I am exploring advanced virtualization performance techniques, and one of those strategies involves subscribing to APIs with less re-renders. For more fixed height virtual elements, this API should re-render a bit less.
> feat(virtual-core) add getVirtualIndexesAPI

- packages/virtual-core/src/index.ts
Fixes #931
This fixes a regression caused by PR #864, which adjusted the center alignment of `scrollToIndex` to center on the item. That change moved the center alignment adjustment from `getOffsetForAlignment` into `getOffsetForIndex`. However, `scrollToOffset` also relied on the former function, and now it lacks an implementation for `align: center`.
This PR restores the center alignment to `getOffsetForAlignment`, but adds a new `itemSize` parameter. This lets us share the center alignment implementation with both scroll functions, while also taking the item size into account when calculating the center alignment for `scrollToIndex`.
> fix(virtual-core): fixes center alignment option for scrollToOffset

- examples/react/dynamic/src/main.tsx
- examples/react/fixed/src/main.tsx
- examples/react/infinite-scroll/src/main.tsx
- examples/react/padding/src/main.tsx
- examples/react/scroll-padding/src/main.tsx
- examples/react/smooth-scroll/src/main.tsx
- examples/react/sticky/src/main.tsx
- examples/react/table/src/main.tsx
- examples/react/variable/src/main.tsx
- examples/react/window/src/main.tsx
Similar changes needed across the other examples! (Feel free to push to this PR; I will try to if I find time later.)
> examples: "application is build" -> "application is built"

- examples/react/dynamic/src/main.tsx
I found an invalid link in example code.
So I removed it.
The `window-list` example was moved to another page in #614 .
It seems the item was just forgotten to be deleted.
> examples(react): remove missing link in react dynamic example

- docs/installation.md
As "Copy" button copies the whole content, `$ npm install ...` would copy the dollar sign too, but it's redundant and not a valid command to run. I removed it to keep consistent and provide the best UX for tanstack users.
> docs: update installation commands

- docs/api/virtualizer.md
the explanation of [onChange](https://tanstack.com/virtual/latest/docs/api/virtualizer#onchange) in the official documentation and the actual code do not match, as the sync parameter is missing.
so, i have modified the `docs/api/virtualizer.md` file.
[go to page](https://tanstack.com/virtual/latest/docs/api/virtualizer#onchange)
[go to line](https://github.com/TanStack/virtual/blob/7a3d541d55d7942b3202c1c38e3a9ab5f8ee86cd/packages/virtual-core/src/index.ts#L319)
```typescript
export interface VirtualizerOptions<
TScrollElement extends Element | Window,
TItemElement extends Element,
> {
// omit other source code...
onChange?: (
instance: Virtualizer<TScrollElement, TItemElement>,
sync: boolean,
) => void
```
> docs: add missing parameter to onChange API

- docs/api/virtualizer.md
the description for the sync parameter of the `onChange` function was missing from the API documentation,
so I've added it.
upon reviewing the internal code, i found that it is invoked by the `notify` function.
> specifically through: `maybeNotify`, `resizeItem`, `measure`
https://github.com/TanStack/virtual/blob/721bf538386482d201c1e1bff1a976c5997a90c9/packages/virtual-core/src/index.ts#L447
https://github.com/TanStack/virtual/blob/721bf538386482d201c1e1bff1a976c5997a90c9/packages/virtual-core/src/index.ts#L462
https://github.com/TanStack/virtual/blob/721bf538386482d201c1e1bff1a976c5997a90c9/packages/virtual-core/src/index.ts#L827
https://github.com/TanStack/virtual/blob/721bf538386482d201c1e1bff1a976c5997a90c9/packages/virtual-core/src/index.ts#L1072
> docs: add documentation for sync parameter of the onChange function.

- package.json
pnpm needs to be able to write a new lockfile (hence no-frozen-lockfile) to sync the dependency updates to examples
> ci: fix changeset version script

- .changeset/mean-lamps-shake.md
- packages/virtual-core/src/index.ts
- packages/virtual-core/src/utils.ts
The issue here was that rage was changed by getVirtualIndexes but that was not updating cache in maybeNotify that was it was not calling the notify. 
Fixes #871
> fix(virtual-core): update maybeNotify cache when deps change

- .changeset/tall-masks-call.md
- packages/virtual-core/src/index.ts
This ensures calculateRange returns a valid range when there are fewer items than lanes (including single-item virtual lists). Prevents invalid access to undefined measurements and avoids empty or broken virtual ranges.
Fixes #963
> fix(core): handle case when item count is less than or equal to lanes

- packages/virtual-core/src/index.ts
- packages/virtual-core/tests/index.test.ts
This is a follow-up to #961. The original issue still occurs when there's only one item in a multi-lane layout.
This PR changes the loop condition in `getTotalSize()` to handle cases where only one item exists in multi-lane. The previous condition skipped the loop when `endIndex === 0`, which caused the total size to be incorrectly calculated as 0.
I used the following test to verify the fix locally:
```ts
test("should return correct total size with single item in multi-lane", () => {
const virtualizer = new Virtualizer({
count: 1,
lanes: 2,
getScrollElement: () => null,
estimateSize: () => 50,
scrollToFn: vi.fn(),
observeElementRect: vi.fn(),
observeElementOffset: vi.fn(),
});
expect(virtualizer.getTotalSize()).toBe(50);
});
```
This is a fairly specific edge case, so I didn’t include …
> fix(virtual-core): fix total size calculation for single item in multi-lane

- .changeset/fluffy-books-attend.md
- packages/virtual-core/src/index.ts
- packages/virtual-core/src/utils.ts
> fix(virtual-core): loosen approxEqual to allow 1px difference

- docs/api/virtualizer.md
Updated docs to also include conditional rendering use case for initialOffset (see https://github.com/TanStack/virtual/issues/1038)
> Update docs on initialOffset
