rollup.config.js
Correct the output name of rollup configuration.
=> chore: correct output name

types/index.d.ts
=> fix: add module declaration to types file

types/index.d.ts
=> chore: implement types

src/index.js
Prevent creating a reversed array on every scroll event by memoizing reversed array.
=> optimise measurements calculation

examples/sandbox/src/InfiniteScroll.js
=> fix(examples): SSL in infinite scroll example

src/index.js
Fixes https://github.com/tannerlinsley/react-virtual/issues/63
=> fix: range reacts on container dimension change

README.md
=> docs: improve description of prop 'size'

package.json, yarn.lock
=> chore: remove ts-toolbelt

src/index.js, src/tests/index.test.js
=> fix: measureRef infinite loop in firefox while zoom

README.md, src/index.js, src/tests/index.test.js, types/index.d.ts
=> feat: add rangeExtractor

.gitignore, docs/adapters/solid-virtual.md, package.json, packages/solid-virtual/package.json, packages/solid-virtual/src/index.tsx, packages/solid-virtual/tsconfig.json, rollup.config.ts
Hello! 
Hope you had a wonderful weekend. This pull request aims to add the SolidJS Adapter for @tanstack/virtual. Some things to note here. 
- This adapter wraps all `Virtualizer` instances inside a proxy object. This was done to preserve the reactivity of the `getVirtualItems` and `getTotalSize` methods. This makes the virtualizer instance easy to use in `createEffect` functions. And it works with iterative utilities like `For` out of the box.
- I am using `createComputed` and `mergeProps` functions for the Virtualizer `options` object to allow users to pass signals in the constructor options. This helps in dynamically updating properties like `count`, `getScrollElement` functions when they are updated/mounted/unmounted
- One other interesting thing to point out is that, when we use …
=> feat: Add Solid JS Virtual Adapter

packages/virtual-core/src/index.ts
We can do small optimization in dynamic mode, to cache measureElement for current virtual items when passed as ref, then react will not call it twice during updates, more at
https://reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs
=> refactor: cache measureElement method for current virtual items

docs/api/virtualizer.md
=> Document scrollPaddingStart and scrollPaddingEnd

packages/virtual-core/src/index.ts
https://github.com/TanStack/virtual/discussions/334
=> Improve performance when scrolling or resizing

packages/virtual-core/src/index.ts
Fixes https://github.com/TanStack/virtual/issues/351
=> Fix calling `scrollToOffset()` twice

packages/virtual-core/package.json
Fixes https://github.com/TanStack/virtual/actions/runs/2786194990
Related https://github.com/TanStack/virtual/pull/360
=> fix: Update package.json CJS entry file path

packages/virtual-core/src/index.ts
@tannerlinsley this should reduce the flickering reported at #381 
Idea here is that rather blocking with scrollCheckFrame, as there can be mulit adjustment till scroll happen accumulate them on pendingScrollOffset.
=> fix: reduce flickering on scrolling when measuring

packages/virtual-core/src/index.ts
=> fix(virtual-core): ResizeObserver is not defined in SSR

packages/react-virtual/src/index.tsx, packages/solid-virtual/src/index.tsx, packages/svelte-virtual/src/index.ts, packages/virtual-core/src/index.ts
* smooth scroll not enabled by default
* drop enableSmoothScroll
* replace canSmooth with scroll behavior
* move adjustments logic in dynamic case to scroll method
=> refactor: scroll handling

examples/react/dynamic/src/main.tsx, packages/virtual-core/src/index.ts
=> fix: observe elements after cleanup

packages/react-virtual/__tests__/index.test.tsx, packages/virtual-core/src/index.ts, packages/virtual-core/src/utils.ts
=> fix: calculate range when getting items

packages/react-virtual/__tests__/index.test.tsx, packages/virtual-core/src/index.ts, packages/virtual-core/src/utils.ts
=> fix: scroll to index out of range

packages/virtual-core/src/index.ts, packages/virtual-core/src/utils.ts
=> fix: notify on range change

packages/virtual-core/src/index.ts
TODO: compare perfomance using content rect ResizeObserver callback to calling getBoundingClientRect, will the [layout thrashing] really happen (https://web.dev/avoid-large-complex-layouts-and-layout-thrashing/#avoid-forced-synchronous-layouts)
=> refactor: use ResizeObserver entry

docs/api/virtual-item.md, docs/api/virtualizer.md
Behold, a monumental code improvement.
Just kidding... I was reading the docs and noticed a typo 🤷
=> 📚 [Docs] Fix typo in virtualizer.md

examples/react/fixed/src/main.tsx
just fixed undefined cannot assign to Element | null in example
=> Fixed typescript type error in fixed height react virtual example

packages/virtual-core/src/index.ts
=> fix: getItemKey is called with invalid index

packages/react-virtual/src/index.tsx, packages/solid-virtual/src/index.tsx, packages/svelte-virtual/src/index.ts, packages/virtual-core/src/index.ts, packages/vue-virtual/src/index.ts
=> fix: useWindowVirtualizer locking scrolling position

packages/react-virtual/__tests__/index.test.tsx, packages/virtual-core/__tests__/index.test.ts, packages/virtual-core/src/index.ts
=> fix: calculate range when outer size is defined and count > 0

packages/virtual-core/src/index.ts
This fixes #647 for us.
---
React 18: https://codesandbox.io/p/devbox/suspicious-orla-wcmzp8?file=%2Fsrc%2Fmain.tsx%3A96%2C37
React 16: https://codesandbox.io/p/devbox/funny-sound-9dvq49?file=%2Fsrc%2Fmain.tsx%3A92%2C34
React 16 with this fix: https://codesandbox.io/p/sandbox/amazing-shaw-gnjd9f?file=%2Fsrc%2Fvirtual%2Fcore%2Findex.ts%3A659%2C22
=> Fix: Scroll offset with dynamic sizes not working properly in React 16

packages/virtual-core/src/index.ts
fixing: https://github.com/TanStack/virtual/issues/654
=> fix: sort items by index in case they end in the same position

.github/workflows/ci.yml, .github/workflows/pr.yml, .nx/workflows/dynamic-changesets.yaml
- Use shared setup action from tanstack/config
- Remove dynamic-changesets
=> ci: Optimise GH workflow

docs/config.json, docs/installation.md, docs/introduction.md
Add documentation links and configurtion for Lit Virtual
=> docs: add documentation links to Lit Virtual

packages/lit-virtual/README.md
Add a readme file for Lit adapter.
Closes #762
=> docs: add readme for @tanstack/lit-virtual

.github/renovate.json, .github/workflows/pr.yml
Enable automerge, lockfile maintenance
=> ci(renovate): update renovate config

examples/react/infinite-scroll/src/main.tsx
- fix type error in infinite scroll example
=> Fix: Modify type error in infinite scroll example

examples/react/infinite-scroll/src/main.tsx
- This PR fixes the pagination issues introduced in #781. 
Sorry 😅
=> chore(examples): Resolve duplicate first page and incorrect rendering start introduced in #781

.changeset/honest-snakes-change.md, packages/virtual-core/src/index.ts
This reverts commit b3b7e7dc8b25daeebbd2da61b3b7ae3448babbdb.
=> Revert "Adapt default logic to adjust scroll position only on backward scrolling (#1002)"
